# Generated by Django 5.0.1 on 2024-01-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_delete_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='skill',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
