# Generated by Django 5.0.1 on 2024-01-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='category',
        ),
        migrations.RemoveField(
            model_name='request',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='request',
            name='date',
        ),
        migrations.RemoveField(
            model_name='request',
            name='mechanic',
        ),
        migrations.RemoveField(
            model_name='request',
            name='problem_description',
        ),
        migrations.RemoveField(
            model_name='request',
            name='status',
        ),
        migrations.RemoveField(
            model_name='request',
            name='vehicle_brand',
        ),
        migrations.RemoveField(
            model_name='request',
            name='vehicle_model',
        ),
        migrations.RemoveField(
            model_name='request',
            name='vehicle_name',
        ),
        migrations.RemoveField(
            model_name='request',
            name='vehicle_no',
        ),
        migrations.AddField(
            model_name='request',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='experienceLevel',
            field=models.CharField(choices=[('Entry Level', 'Entry Level'), ('Mid Level', 'Mid Level'), ('Senior Level', 'Senior Level')], default='Entry Level', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='positionDomain',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='positionRole',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='projectInformation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='startDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='technology',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='workLocation',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
