# Generated by Django 5.0.1 on 2024-01-15 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_remove_request_category_remove_request_cost_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
