# Generated by Django 3.0.5 on 2024-01-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_request_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='master_agreements',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
