# Generated by Django 4.1 on 2024-01-23 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_request_master_agreements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='email',
        ),
    ]
