# Generated by Django 4.1 on 2024-01-27 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_rename_address_customer_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Mechanic',
        ),
    ]
